<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">readFile</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgYyA9IHBpcGVsaW5lLmdldEN1cnNvcigpOwpTdHJpbmcgZm5hbWUgPSBJRGF0
YVV0aWwuZ2V0U3RyaW5nKGMsICJmbmFtZSIpOwpTdHJpbmcgbG9hZEFzID0gSURhdGFVdGlsLmdl
dFN0cmluZyhjLCAibG9hZEFzIik7ClN0cmluZyBpZ25vcmVFcnJvciA9IElEYXRhVXRpbC5nZXRT
dHJpbmcoYywgImlnbm9yZUVycm9yIik7CgppZiAoZm5hbWUgPT0gbnVsbCkKCXRocm93IG5ldyBT
ZXJ2aWNlRXhjZXB0aW9uKCJwcm92aWRlIGZpbGUgbmFtZSBwbGVhc2UiKTsKCi8vIHByb2Nlc3MK
CmJ5dGVbXSBkYXRhID0gbnVsbDsKSW5wdXRTdHJlYW0gaW4gPSBudWxsOwoKdHJ5IHsKCWlmIChs
b2FkQXMgIT0gbnVsbCAmJiBsb2FkQXMuZXF1YWxzSWdub3JlQ2FzZSgic3RyZWFtIikpIHsKCQlp
biA9IG5ldyBGaWxlSW5wdXRTdHJlYW0obmV3IEZpbGUoZm5hbWUpKTsKCX0gZWxzZSB7CgkJZGF0
YSA9IEZpbGVzLnJlYWRBbGxCeXRlcyhQYXRocy5nZXQoZm5hbWUpKTsKCX0KfSBjYXRjaCAoTm9T
dWNoRmlsZUV4Y2VwdGlvbiBlICkgewoJaWYgKGlnbm9yZUVycm9yID09IG51bGwgfHwgIWlnbm9y
ZUVycm9yLmVxdWFsc0lnbm9yZUNhc2UoInRydWUiKSkKCQl0aHJvdyBuZXcgU2VydmljZUV4Y2Vw
dGlvbihlKTsKfSBjYXRjaCAoSU9FeGNlcHRpb24gZSkgewoJCgl0aHJvdyBuZXcgU2VydmljZUV4
Y2VwdGlvbihlKTsKfQoKLy8gcGlwZWxpbmUgb3V0CgpJRGF0YVV0aWwucHV0KGMsICJuYW1lIiwg
bmV3IEZpbGUoZm5hbWUpLmdldE5hbWUoKSk7CgppZiAoZGF0YSAhPSBudWxsKSB7CgkKCWlmIChs
b2FkQXMgIT0gbnVsbCAmJiBsb2FkQXMuZXF1YWxzSWdub3JlQ2FzZSgic3RyaW5nIikpCgkJSURh
dGFVdGlsLnB1dChjLCAic3RyaW5nIiwgbmV3IFN0cmluZyhkYXRhKSk7CgllbHNlCgkJSURhdGFV
dGlsLnB1dChjLCAiYnl0ZXMiLCBkYXRhKTsKCWMuZGVzdHJveSgpOwp9IGVsc2UgewoJSURhdGFV
dGlsLnB1dChjLCAic3RyZWFtIiwgaW4pOwp9</value>
</Values>
