<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">fileExists</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly9maWxlUGF0aCBwaXBlbGluZSBpbgoKSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBl
bGluZS5nZXRDdXJzb3IoKTsKU3RyaW5nCWZuYW1lID0gSURhdGFVdGlsLmdldFN0cmluZyhwaXBl
bGluZUN1cnNvciwgImZuYW1lIik7CgovLyBwcm9jZXNzCgpib29sZWFuIGV4aXN0cyA9IG5ldyBG
aWxlKGZuYW1lKS5leGlzdHMoKTsKYm9vbGVhbiBpc0RpciA9IG5ldyBGaWxlKGZuYW1lKS5pc0Rp
cmVjdG9yeSgpOwoKU3RyaW5nIGNoaWxkTmFtZSA9IG51bGw7CgppZiAoaXNEaXIpIHsKCVN0cmlu
Z1tdIGZpbGVzID0gbmV3IEZpbGUoZm5hbWUpLmxpc3QoKTsKCQoJaWYgKGZpbGVzLmxlbmd0aCA+
IDApIHsKCQljaGlsZE5hbWUgPSBmaWxlc1tmaWxlcy5sZW5ndGgtMV07Cgl9IGVsc2UgewoJCWV4
aXN0cyA9IGZhbHNlOwoJfQp9CgovLyBwaXBlbGluZSBvdXQKCklEYXRhVXRpbC5wdXQocGlwZWxp
bmVDdXJzb3IsICJleGlzdHMiLCAiIiArIGV4aXN0cyk7CgppZiAoZXhpc3RzKSB7CglJRGF0YVV0
aWwucHV0KHBpcGVsaW5lQ3Vyc29yLCAiaXNEaXIiLCAiIiArIGlzRGlyKTsKCQoJaWYgKGNoaWxk
TmFtZSAhPSBudWxsKSB7CgkJSURhdGFVdGlsLnB1dChwaXBlbGluZUN1cnNvciwgImZvdW5kIiwg
bmV3IEZpbGUobmV3IEZpbGUoZm5hbWUpLCBjaGlsZE5hbWUpLmdldFBhdGgoKSk7Cgl9Cn0KCnBp
cGVsaW5lQ3Vyc29yLmRlc3Ryb3koKTs=</value>
</Values>
